version: "2.0"

services:
  markdown:
    container_name: ${CONTAINER_NAME}
    build:
      context: ./
      dockerfile: Dockerfile
    image: markdown_notes
    volumes:
      - ${FILES}:/var/www/html/public/files
    user: nobody
    ports:
      - 8080:8080
